Bug fixes from review
node-red/node-red-dev-cli pull request #3
Opened 2021-10-22 17:50 UTC by sammachin

2021-11-01 15:33 UTC, dceejay reviewed
looks all good to me

2021-11-16 00:09 UTC, knolleary requested changes

2021-11-16 00:09 UTC, knolleary commented on docs/P01.md
> +The package.json MUST contain a key of `license` that specfies the type of license used, this can be either an open source licence or your own propriataty license. The value should be either a recogn
```suggestion
The package.json MUST contain a key of `license` that specifies the type of license used, this can be either an open source licence or your own proprietary license. The value should be either a recognised [SPDX ID](https://spdx.org/licenses/) Or refer to a filename within the package for a custom license.
```

2021-11-16 00:09 UTC, knolleary commented on docs/P02.md
> +This is to check for forked nodes where the publisher has forked an original repo and publihsed the node under a new name but not updated the repo to point to their own new copy. This can result in a
```suggestion
This is to check for forked nodes where the publisher has forked an original repo and published the node under a new name but not updated the repo to point to their own new copy. This can result in authors of the original node getting issues raised against their repository for a downstream fork.
```

2021-11-16 00:09 UTC, knolleary commented on docs/P02.md
> +https://docs.npmjs.com/cli/v7/configuring-npm/package-json#name
```suggestion
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository
```

2021-11-16 00:09 UTC, knolleary commented on docs/P02.md
> +This test may fail where you are validating a local copy of the package and it has not yet been published, or where the code has not been published in a repoository.
```suggestion
This test may fail where you are validating a local copy of the package and it has not yet been published, or where the code has not been published in a repository.
```

2021-11-16 00:09 UTC, knolleary commented on docs/P04.md
> +New pacakges published to npm after 1st December 2021 should use a scoped name, they may then use any value in their pacakge name eg `@devname/acme-node-red`
I remain on the fence about this. Certainly not sure we're at a point to put a date on this. Needs discussion and consensus with the dev community.

```suggestion
New packages published to npm after 1st December 2021 should use a scoped name, they may then use any value in their package name eg `@devname/acme-node-red`
```

2021-11-16 00:09 UTC, knolleary commented on docs/P04.md
> +Scoped names also allow for a developer to fork an abandoned node and publish a new version with the same pacakge name but within their scope. This makes it clearer to users where multiple pacakges e
```suggestion
Scoped names also allow for a developer to fork an abandoned node and publish a new version with the same package name but within their scope. This makes it clearer to users where multiple packages exist.
```

2021-11-16 00:09 UTC, knolleary commented on docs/P05.md
> +This identifies the package as Node-RED modules rather than a more generic node package
```suggestion
This identifies the package as Node-RED modules rather than a more generic node package.

Without this keyword set, it will not be listed on the Flow Library.
```

2021-11-16 00:09 UTC, knolleary commented on docs/P06.md
> +With the `node-red` sectio of the package.json file the developer SHOULD indicate the mnimum supported version. This must staisfy at least one of the current `latest` or `maintanance` tagged releases
If we're going to say they need to have this, then the creating nodes docs need to be updated to include this to match.

```suggestion
Within the `node-red` section of the package.json file the developer SHOULD indicate the minimum supported version. This must satisfy at least one of the current `latest` or `maintenance` tagged releases.
```

2021-11-16 00:09 UTC, knolleary commented on docs/P07.md
> +Within the `engines` section of the package.json file you SHOULD declare the minimum version of Node that your pacakge works on.
```suggestion
Within the `engines` section of the package.json file you SHOULD declare the minimum version of Node that your package works on.
```

2021-11-16 00:09 UTC, knolleary commented on docs/P07.md
> +Node-RED has supported multiple versions of Node in its history and some of these have become end of life, this helps users identify if a node will run on their
Missing the end of the sentence?

2021-11-16 00:09 UTC, knolleary commented on docs/P08.md
> +The tool will check for pacakges of the same name with a different scope and these may be highlighted to the user.
```suggestion
The tool will check for packages of the same name with a different scope and these may be highlighted to the user.
```

2021-11-18 15:27 UTC, sammachin commented on docs/P06.md
> +With the `node-red` sectio of the package.json file the developer SHOULD indicate the mnimum supported version. This must staisfy at least one of the current `latest` or `maintanance` tagged releases
This is only a "should" requirement not a "must", the docs currently say that you "can" I guess we could change to that to also say shoud?

2021-12-14 10:10 UTC, sammachin commented on docs/P06.md
> +With the `node-red` sectio of the package.json file the developer SHOULD indicate the mnimum supported version. This must staisfy at least one of the current `latest` or `maintanance` tagged releases
Node-RED Docs were updated in https://github.com/node-red/node-red.github.io/pull/251

2021-12-14 10:16 UTC, knolleary requested changes
Couple more suggested doc tweaks.

2021-12-14 10:16 UTC, knolleary commented on docs/P05.md
> +Without this keyword set, it will not be listed on the Flow Library.
```suggestion
This identifies the package as a Node-RED module rather than a more generic node package.

Without this keyword set, it will not be listed on the Flow Library, but it will still be npm installable.

If the module is not yet ready for wider use by the Node-RED community, you should not include the keyword.
```

2021-12-14 10:16 UTC, knolleary commented on docs/D01.md
> +This isn't meant to be a hard limit just a warning to check that everything in your dependencies list is indeed needed, its is recognised that some packages may have a legitimate reason to have a lot
```suggestion
This isn't meant to be a hard limit just a warning to check that everything in your dependencies list is indeed needed, it is recognised that some packages may have a legitimate reason to have a lot of dependencies and this can be noted in the README
```

2021-12-14 10:44 UTC, merged